future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: academicpages
url: https://nickbadams.github.io/group-meeting 
name: Nick Adams
description: An initial blog and site
twitter: yourtwitterhandle
calendar: https://yourcalendarurl
mailinglist: https://yourmailinglisturl
gravatar_url: 
disqus_username:
